spring:
  output:
    ansi:
      enabled: always
  # Cấu hình môi trường đang chạy (dev/test/prod)
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuighetlaptrinh@gmail.com
    password: rrtrdpjstovvjphw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Cấu hình thông tin kết nối Database (MySQL)
  datasource:
    url: jdbc:mysql://localhost:3307/tuannehehe # URL kết nối DB
    username: root                             # Tên đăng nhập DB
    password: Iamtuanne                    # Mật khẩu DB
    driver-class-name: com.mysql.cj.jdbc.Driver # Driver MySQL JDBC

    hikari:
      maximum-pool-size: 20       # Số kết nối tối đa trong pool (default: 10)
      minimum-idle: 5             # Số kết nối rảnh tối thiểu
      idle-timeout: 30000         # Đóng connection nếu idle quá 30s
      connection-timeout: 30000   # Timeout khi lấy connection (30s)
      pool-name: MyHikariCP       # Tên pool (tùy chọn)

  rabbitmq:
    host: localhost
    port: 5672
    username: tuanne
    password: 2542004Tuan@

  # Cấu hình Redis (cache, rate-limit, session...)
  redis:
    host: localhost
    port: 6378
    lettuce:
      pool:
        max-active: 10           # Số kết nối tối đa Redis
        max-idle: 5              # Số connection Redis có thể "rảnh"
        min-idle: 1              # Số connection "rảnh" tối thiểu
        max-wait: 1000           # Timeout khi lấy connection (ms)

  # Cấu hình JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: update           # Tự tạo/sửa bảng khi entity thay đổi (dev ONLY)
    show-sql: true               # In câu SQL ra console
#    properties:
#      hibernate:
#        format_sql: true         # In SQL có format dễ đọc
#        dialect: org.hibernate.dialect.MySQL8Dialect # Dialect cho MySQL

  # Cấu hình Tomcat Embedded (Server HTTP)
  servlet:
    context-path: /              # Đường dẫn gốc của app

  server:
    port: 8080                   # Cổng mặc định chạy app
    tomcat:
      max-threads: 200           # Số thread tối đa phục vụ request
      min-spare-threads: 10      # Thread nhàn rỗi tối thiểu

# Cấu hình Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs           # Endpoint API docs
  swagger-ui:
    path: /swagger-ui.html       # Endpoint giao diện Swagger UI
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

# Cấu hình JWT
tuanne:
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
    access-token-validity-in-seconds: 8640000     # Thời gian sống access token (100 ngày)
    refresh-token-validity-in-seconds: 8640000     # Thời gian sống refresh token (100 ngày)

# Logging nâng cao (tùy chọn)
#logging:
#  level:
#    root: INFO                         # Log toàn hệ thống
#    org.springframework.web: DEBUG     # Log chi tiết Spring Web
#    com.teamphacode: DEBUG             # Log riêng package dự án bạn
#    org.hibernate.SQL: DEBUG           # In SQL
#    org.hibernate.type.descriptor.sql: TRACE     # In giá trị parameters (rất chi tiết)
#
