spring:
  profiles:
    active: dev
  application:
    name: Tuanne
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/Merchant
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

tuanne:
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
    access-token-validity-in-seconds: 8640000
    refresh-token-validity-in-seconds: 8640000
logging:
  level:
    org.springframework: DEBUG # Bật log DEBUG cho toàn bộ Spring
    org.springframework.aop: TRACE # Bật log TRACE (chi tiết nhất) cho AOP