version: '3.7'

services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./.docker/data/db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: Iamtuanne   # mật khẩu root mới
      MYSQL_DATABASE: merchant         # tên database
    ports:
      - "3307:3306"

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./.docker/data/redis:/data
    ports:
      - "6378:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: tuanne
      RABBITMQ_DEFAULT_PASS: 2542004Tuan@
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/data/rabbitmq:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # tắt security để dev cho dễ
      - ES_JAVA_OPTS=-Xms1g -Xmx1g     # memory cho ES
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.docker/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always
